CREATE TABLE ESCOLA(
    NOME VARCHAR2(30),
    TELEFONE VARCHAR2(20) NOT NULL,
    EMAIL VARCHAR2(30),
    TELEFONE_COMISSAO VARCHAR2(20) NOT NULL,
    EMAIL_COMISSAO VARCHAR2(30),
    
    CONSTRAINT PK_ESCOLA PRIMARY KEY (NOME)
);


CREATE TABLE ATRACAO_EXTRA(
    CNPJ VARCHAR2(30),
    NOME VARCHAR2(30) NOT NULL,
    TELEFONE VARCHAR2(20) NOT NULL,
    EMAIL VARCHAR2(30),
    DESCRICAO VARCHAR2(100),
    
    CONSTRAINT PK_ATRACAO_EXTRA PRIMARY KEY(CNPJ)
);


CREATE TABLE BANDA(
    CPF_LIDER VARCHAR2(20),
    NOME VARCHAR2(30) NOT NULL,
    
    CONSTRAINT PK_BANDA PRIMARY KEY(CPF_LIDER)
);


CREATE TABLE FOTOGRAFIA(
    CNPJ VARCHAR2(30),
    NRO_FOTOGRAFOS NUMBER,
    NOME VARCHAR2(20) NOT NULL,
    TIPO VARCHAR2(9) NOT NULL,
    
    CONSTRAINT PK_FOTOGRAFIA PRIMARY KEY(CNPJ),
    CONSTRAINT TIPO_FOTOGRAFIA CHECK (UPPER(TIPO) IN ('COBERTURA', 'ENSAIO'))
);


CREATE TABLE CASA_FESTAS(
    CEP VARCHAR2(10),
    NRO NUMBER,
    NOME VARCHAR2(20) NOT NULL,
    RUA VARCHAR2(20),
    COMPLEMENTO VARCHAR2(40),
    BAIRRO VARCHAR2(20),
    CIDADE VARCHAR2(20),
    LOTACAO NUMBER,
    
    CONSTRAINT PK_CASA_FESTAS PRIMARY KEY(CEP, NRO)
);


CREATE TABLE DECORADORA(
   CNPJ VARCHAR2(30),
   NOME VARCHAR2(20),
   DESCRICAO VARCHAR2(60),
   
   CONSTRAINT PK_DECORADORA PRIMARY KEY(CNPJ)
);


CREATE TABLE TELEFONES_BANDA(
    BANDA VARCHAR2(20),
    TELEFONE VARCHAR2(20),
    
    CONSTRAINT PK_TELEFONES_BANDA PRIMARY KEY(BANDA, TELEFONE),
    CONSTRAINT FK_TELEFONE_BANDA FOREIGN KEY(BANDA) REFERENCES BANDA(CPF_LIDER) ON DELETE CASCADE

);


CREATE TABLE EMAILS_BANDA(
    BANDA VARCHAR2(20),
    EMAIL VARCHAR2(30),
    
    CONSTRAINT PK_EMAILS_BANDA PRIMARY KEY(BANDA, EMAIL),
    CONSTRAINT FK_EMAILS_BANDA FOREIGN KEY(BANDA) REFERENCES BANDA(CPF_LIDER) ON DELETE CASCADE

);


CREATE TABLE INTEGRANTES_BANDA(
    BANDA VARCHAR2(20),
    NOME_INTEGRANTE VARCHAR2(30),
    
    CONSTRAINT PK_INTEGRANTES_BANDA PRIMARY KEY(BANDA, NOME_INTEGRANTE),
    CONSTRAINT FK_INTEGRANTES_BANDA FOREIGN KEY(BANDA) REFERENCES BANDA(CPF_LIDER) ON DELETE CASCADE

);


CREATE TABLE ESTILOS_BANDA(
    BANDA VARCHAR2(20),
    ESTILO VARCHAR2(10),
    
    CONSTRAINT PK_ESTILOS_BANDA PRIMARY KEY(BANDA, ESTILO),
    CONSTRAINT FK_ESTILOS_BANDA FOREIGN KEY(BANDA) REFERENCES BANDA(CPF_LIDER) ON DELETE CASCADE

);


CREATE TABLE EMAILS_FOTOGRAFIA(
    FOTGRF VARCHAR2(30),
    EMAIL VARCHAR2(30),
    
    CONSTRAINT PK_EMAILS_FOTOGRAFIA PRIMARY KEY(FOTGRF, EMAIL),
    CONSTRAINT FK_EMAILS_FOTOGRAFIA FOREIGN KEY(FOTGRF) REFERENCES FOTOGRAFIA(CNPJ) ON DELETE CASCADE
);


CREATE TABLE TELEFONES_FOTOGRAFIA(
    FOTGRF VARCHAR2(30),
    TELEFONE VARCHAR2(30),
    
    CONSTRAINT PK_TELEFONES_FOTOGRAFIA PRIMARY KEY(FOTGRF, TELEFONE),
    CONSTRAINT FK_TELEFONES_FOTOGRAFIA FOREIGN KEY(FOTGRF) REFERENCES FOTOGRAFIA(CNPJ) ON DELETE CASCADE
);


CREATE TABLE EMAILS_DECORADORA(
    DEC VARCHAR2(30),
    EMAIL VARCHAR2(30),
    
    CONSTRAINT PK_EMAILS_DECORADORA PRIMARY KEY(DEC, EMAIL),
    CONSTRAINT FK_EMAILS_DECORADORA FOREIGN KEY(DEC) REFERENCES DECORADORA(CNPJ) ON DELETE CASCADE
);


CREATE TABLE TELEFONES_DECORADORA(
    DEC VARCHAR2(30),
    TELEFONE VARCHAR2(20),
    
    CONSTRAINT PK_TELEFONES_DECORADORA PRIMARY KEY(DEC, TELEFONE),
    CONSTRAINT FK_TELEFONE_DECORADORA FOREIGN KEY(DEC) REFERENCES DECORADORA(CNPJ) ON DELETE CASCADE

);


CREATE TABLE EVENTO(
        DATA DATE,
        FOTOGRAFIA VARCHAR2(30),
        NRO_CASA_FESTAS NUMBER,
        CEP_CASA_FESTAS VARCHAR2(10),
        TIPO VARCHAR2(9) NOT NULL,
                
        CONSTRAINT PK_EVENTO PRIMARY KEY(DATA),
        CONSTRAINT FK1_ENVENTO FOREIGN KEY(FOTOGRAFIA) REFERENCES FOTOGRAFIA(CNPJ) ON DELETE SET NULL,
        CONSTRAINT FK2_EVENTO FOREIGN KEY(NRO_CASA_FESTAS, CEP_CASA_FESTAS) REFERENCES CASA_FESTAS(NRO, CEP) ON DELETE SET NULL ,
        CONSTRAINT TIPO_EVENTO CHECK (UPPER(TIPO) IN ('CASAMENTO', 'FORMATURA'))
        
);


CREATE TABLE FORMATURA(
    DATA DATE,
    ESCOLA VARCHAR2(30) NOT NULL,
    NOME_CERIMONIALISTA_MISSA VARCHAR2(20),
    NRO_CONVIDADOS NUMBER,
    DATA_COLACAO DATE NOT NULL,
    
    CONSTRAINT PK_FORMATURA PRIMARY KEY(DATA),
    CONSTRAINT FK1_FORMATURA FOREIGN KEY(DATA) REFERENCES EVENTO(DATA) ON DELETE CASCADE,
    CONSTRAINT FK2_FORMATURA FOREIGN KEY(ESCOLA) REFERENCES ESCOLA(NOME) ON DELETE CASCADE
);


CREATE TABLE BANDA_SE_APRESENTA(
    DATA_EVENTO DATE,
    BANDA VARCHAR2(20),
    HORA_INI DATE, 
    HORA_FIM DATE, 
    
    CONSTRAINT PK_BANDA_SE_APRESENTA PRIMARY KEY(DATA_EVENTO, BANDA),
    CONSTRAINT FK1_BANDA_SE_APRESENTA FOREIGN KEY(DATA_EVENTO) REFERENCES EVENTO(DATA) ON DELETE CASCADE,
    CONSTRAINT FK2_BANDA_SE_APRESENTA FOREIGN KEY(BANDA) REFERENCES BANDA(CPF_LIDER) ON DELETE CASCADE,
	CONSTRAINT CK_BANDA_SE_APRESENTA CHECK(EXTRACT(MONTH FROM DATA_EVENTO) = EXTRACT(MONTH FROM HORA_INI) 
				AND 
				EXTRACT(DAY FROM DATA_EVENTO) = EXTRACT(DAY FROM HORA_INI)
				AND
				EXTRACT(YEAR FROM DATA_EVENTO) = EXTRACT(YEAR FROM HORA_INI)
				AND
				HORA_INI < HORA_FIM
			)
);


CREATE TABLE DECORA(	
    DATA_EVENTO DATE,
    DECORADORA VARCHAR2(30) NOT NULL,
    
    CONSTRAINT PK_DECORA PRIMARY KEY(DATA_EVENTO),
    CONSTRAINT FK1_DECORA FOREIGN KEY(DATA_EVENTO) REFERENCES EVENTO(DATA) ON DELETE CASCADE,
    CONSTRAINT FK2_DECORA FOREIGN KEY(DECORADORA) REFERENCES DECORADORA(CNPJ) ON DELETE CASCADE
);


CREATE TABLE FORMATURA_TEM_ATREXTRA(
    ATREXTRA VARCHAR2(30),
    DATA_FORMATURA DATE,
    
    CONSTRAINT PK_FORMATURA_TEM_ATREXTRA PRIMARY KEY(ATREXTRA, DATA_FORMATURA),
    CONSTRAINT FK1_FORMATURA_TEM_ATREXTRA FOREIGN KEY(ATREXTRA) REFERENCES ATRACAO_EXTRA(CNPJ) ON DELETE CASCADE,
    CONSTRAINT FK2_FORMATURA_TEM_ATREXTRA FOREIGN KEY(DATA_FORMATURA) REFERENCES FORMATURA(DATA) ON DELETE CASCADE
);


CREATE TABLE PARANINFO(
    NOME VARCHAR2(20),
    TELEFONE VARCHAR2(20) NOT NULL,
    
    CONSTRAINT PK_PARANINFO PRIMARY KEY(NOME)
);


CREATE TABLE PARANINFO_FORMATURA(
    PARANINFO VARCHAR2(20),
    DATA_FORMATURA DATE,
    
    CONSTRAINT PK_PARANINFO_FORMATURA PRIMARY KEY(PARANINFO, DATA_FORMATURA),
    CONSTRAINT FK1_PARANINFO_FORMATURA FOREIGN KEY(PARANINFO) REFERENCES PARANINFO(NOME) ON DELETE CASCADE,
    CONSTRAINT FK2_PARANINFO_FORMATURA FOREIGN KEY(DATA_FORMATURA) REFERENCES FORMATURA(DATA) ON DELETE CASCADE
);


CREATE TABLE LISTA_FORMANDOS(
    DATA_FORMATURA DATE,
    NOME_FORMANDO VARCHAR2(20),
    
    CONSTRAINT PK_LISTA_FORMANDOS PRIMARY KEY(DATA_FORMATURA, NOME_FORMANDO),
    CONSTRAINT FK_LISTA_FORMANDOS FOREIGN KEY(DATA_FORMATURA) REFERENCES FORMATURA(DATA) ON DELETE CASCADE
);
